export const CLICK_TO_SEND_LOGIN = "CLICK_TO_SEND_LOGIN";

export const CLICK_TO_ADD_TODO = "CLICK_TO_ADD_TODO";

export const CLICK_TO_DELETE_TODO = "CLICK_TO_DELETE_TODO";

export const CLICK_TO_COMPLETE_TODO = "CLICK_TO_COMPLETE_TODO";
